[profile.ci]
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci.junit]  # this can be some other profile, too
path = "junit.xml"
store-success-output = true
store-failure-output = true