name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo check
        run: cargo check --lib --all-features
      - name: Run cargo clippy
        run: cargo clippy --all-features --no-deps -- -D warnings

  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend:
          - feature: parry3d
            profile_name: benches
            test_arg: --benches
          - feature: parry3d
            profile_name: parry3d
            test_arg: --test parry3d
          - feature: avian
            profile_name: avian
            test_arg: --test avian
          - feature: rapier
            profile_name: rapier3d
            test_arg: --test rapier3d
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend.profile_name }}
      - name: Install alsalib headers
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: taiki-e/install-action@nextest
      - name: Test with nextest
        run: cargo nextest run --no-default-features --features "${{ matrix.backend.feature }}" ${{ matrix.backend.test_arg }} --profile ${{ matrix.backend.profile_name }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results-${{ matrix.backend.profile_name }}
          path: target/nextest/**/*.xml
          retention-days: 1

  report:
    name: Publish reports
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/*.xml'
          detailed_summary: true
          include_passed: true
          group_suite: true
          comment: true
          annotate_notice: true
