name: Benches

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code.
      uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install alsalib headers
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - uses: boa-dev/criterion-compare-action@v3
      with:
        defaultFeatures: false
        features: "parry3d"
        # The baseline branch.
        # TODO: Move to `github.base_ref` once merged.
        branchName: ${{ github.head_ref }}
